name: Pathogen Evolution Lab
description: evolution epidemiology and phylodynamics
url: http://vjlab.io

markdown: kramdown
permalink: /:categories/:title/
future: true
sass:
    sass_dir: css
    
plugins: ['jekyll-twitter-plugin']


exclude:
  - "*.branches"
  - "*.kml"
  - "*.log"
  - "*.nb"
  - "*.trees"
  - "*.cpp"
  - "*.h"
  - "*.hh"
  - "*.java"
  - "*.jar"
  - "*.csv"
  - "*.tsv"
  - "*.txt"
  - "*.rb"
  - "*.py"
  - "*.class"
  - "*.tips"
  - "*.fasta"
  - "*.nex"
  - "Gemfile"
  - "Gemfile.lock"
  - "s3_website.yml"
  - "blog/_drafts"

projects:
  - vjlab/dips
  - xieruopeng/HKU_HPC2015
  - vjlab/resources  
